version: "3.3"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ${HDD_PATH}/plex/config:/config
      - ${HDD_PATH}/plex/tv:/tv
      - ${HDD_PATH}/plex/movies:/movies
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ${HDD_PATH}/sonarr/config:/config
      - ${HDD_PATH}/plex/tv:/tv
      - ${HDD_PATH}/transmission/downloads:/downloads
    ports:
      - 8989:8989
    networks:
      default:
        ipv4_address: 172.20.0.2
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
    volumes:
      - ${HDD_PATH}/transmission/config:/config
      - ${HDD_PATH}/transmission/downloads:/downloads
      - ${HDD_PATH}/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      default:
        ipv4_address: 172.20.0.3
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - AUTO_UPDATE=true
    volumes:
      - ${HDD_PATH}/jackett/config:/config
    ports:
      - 9117:9117
    networks:
      default:
        ipv4_address: 172.20.0.4
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ${HDD_PATH}/bazarr/config:/config
      - ${HDD_PATH}/plex/movies:/movies
      - ${HDD_PATH}/plex/tv:/tv
    ports:
      - 6767:6767
    networks:
      default:
        ipv4_address: 172.20.0.5
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ${HDD_PATH}/radarr/config:/config
      - ${HDD_PATH}/plex/movies:/movies
      - ${HDD_PATH}/transmission/downloads:/downloads
    ports:
      - 7878:7878
    networks:
      default:
        ipv4_address: 172.20.0.6
    restart: unless-stopped

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

