version: "3.3"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /data/2tb/plex/config:/config
      - /data/2tb/plex/tv:/tv
      - /data/2tb/plex/movies:/movies
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /data/2tb/sonarr/config:/config
      - /data/2tb/plex/tv:/tv
      - /data/2tb/rutorrent/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
    volumes:
      - /data/2tb/transmission/config:/config
      - /data/2tb/transmission/downloads:/downloads
      - /data/2tb/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/2tb/rutorrent/config:/config
      - /data/2tb/rutorrent/downloads:/downloads
    ports:
      - 80:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - AUTO_UPDATE=true
    volumes:
      - /data/2tb/jackett/config:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /data/2tb/bazarr/config:/config
      - /data/2tb/plex/movies:/movies
      - /data/2tb/plex/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
