version: "3.3"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ${PLEX}/config:/config
      - ${TV_SHOWS}:/tv
      - ${MOVIES}:/movies
      - ${PICTURES}:/pictures
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${SONARR}/config:/config
      - ${TV_SHOWS}:/tv
      - ${TORRENT_DOWNLOADS}:/downloads
    ports:
      - 8989:8989
    networks:
      default:
        ipv4_address: 172.20.0.2
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${DELUGE}/config:/config
      - ${TORRENT_DOWNLOADS}:/downloads
    ports:
      - 8112:8112
    networks:
      default:
        ipv4_address: 172.20.0.3
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=true
    volumes:
      - ${JACKETT}/config:/config
    ports:
      - 9117:9117
    networks:
      default:
        ipv4_address: 172.20.0.4
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${BAZARR}/config:/config
      - ${MOVIES}:/movies
      - ${TV_SHOWS}:/tv
    ports:
      - 6767:6767
    networks:
      default:
        ipv4_address: 172.20.0.5
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${RADARR}/config:/config
      - ${MOVIES}:/movies
      - ${TORRENT_DOWNLOADS}:/downloads
    ports:
      - 7878:7878
    networks:
      default:
        ipv4_address: 172.20.0.6
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

  muximux:
    image: linuxserver/muximux
    container_name: muximux
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${MUXIMUX}:/config
    ports:
      - ${MUXIMUX_PORT}:80
    networks:
      default:
        ipv4_address: 172.20.0.7
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --label-enable --cleanup --schedule "0 4 * * *"

  portainer:
    image: portainer/portainer
    container_name: portainer
    network_mode: host
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER}:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

